name: Deploy Laravel + Vue to O2Switch

on:
  push:
    branches:
      - main  # ou master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupérer le code du repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Configurer SSH
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 3️⃣ Déployer sur le serveur avec sécurité
      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no chov2692@revolverealm.com "
          set -e  # Arrêter si une commande échoue

          FRONT_DIR=~/projet-front.revolverealm.com
          SRC_DIR=~/projet.revolverealm.com/ovkhann/PROJET-PHARE
          BACKUP_DIR=~/projet-front-backup-$(date +%Y%m%d%H%M%S)

          echo '🔹 Backup du front actuel...'
          if [ -d \$FRONT_DIR ]; then
            cp -r \$FRONT_DIR \$BACKUP_DIR
            echo \"Backup créé : \$BACKUP_DIR\"
          fi

          echo '🔹 Déploiement du code source...'
          cd \$SRC_DIR
          git pull || { echo 'Erreur git pull'; exit 1; }

          composer install --no-dev --prefer-dist || { echo 'Erreur composer install'; exit 1; }

          npm install || { echo 'Erreur npm install'; exit 1; }
          npm run build || { echo 'Erreur npm run build'; exit 1; }

          echo '🔹 Copie du front compilé...'
          rsync -a --delete dist/ \$FRONT_DIR || { echo 'Erreur rsync'; exit 1; }

          echo '🔹 Nettoyage cache Laravel...'
          php artisan cache:clear || { echo 'Erreur cache clear'; exit 1; }

          echo '✅ Déploiement terminé avec succès !'
          "
